/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.eduplanner;

import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Diego
 */
public class JFrameMenu extends javax.swing.JFrame {
    
    public PilaUsers pila;
    public NodoUsers user;
    public ListSubject list;
    public ListTasks listT;
    public ListExams listE;
    public ListQuestions listQ;
    
    
    //Constructor para inicializar iconos
    public JFrameMenu(PilaUsers pilaUsers, NodoUsers user, ListSubject list, ListTasks listT, ListExams listE, ListQuestions listQ) {
        initComponents();
        
        this.listQ = listQ;
        this.listE = listE;
        this.listT = listT;
        this.user = user;
        this.pila = pilaUsers;
        this.list = list;
        
        
        //IMAGEN DEL CURSOR 

        ImageIcon img = new ImageIcon("C:\\Users\\Diego\\Documents\\NetBeansProjects\\ProyectoFinal\\src\\Recursor\\Cursores\\Cursor2.png");
        
        Cursor c;
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        c = tk.createCustomCursor(img.getImage(), new Point(1,1), null);
        
        jMenuCalAverage.setCursor(c);
        jMenuAgenda.setCursor(c);
        jMenuCarts.setCursor(c);
        jMenuProfile.setCursor(c);
        jMenuReturn.setCursor(c);
        
        jMenuItemRegisterSubject.setCursor(c);
        jMenuItemReport.setCursor(c);
        jMenuItemRecomendation.setCursor(c);
        jMenuItemRegisterHomeWork.setCursor(c);
        jMenuItemRegisterExams.setCursor(c);
        jMenuItemHomeWorkExams.setCursor(c);
        jMenuItemRegisterQuestions.setCursor(c);
        jMenuItemStudie.setCursor(c);
        jMenuItemProfile.setCursor(c);
        jMenuItemReturn.setCursor(c);
        
        ////////////////Titulo de la aplicacion//////////////////////////////
        
        setTitle("EduPlanner");
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        // Icono para la aplicación
        setIconImage(new ImageIcon("C:\\Users\\Diego\\Documents\\NetBeansProjects\\ProyectoFinal\\src\\Recursor\\LogotipoGrande.png").getImage());

        setVisible(true);
    }
    public JFrameMenu(){
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuReturn = new javax.swing.JMenu();
        jMenuItemReturn = new javax.swing.JMenuItem();
        jMenuCalAverage = new javax.swing.JMenu();
        jMenuItemRegisterSubject = new javax.swing.JMenuItem();
        jMenuItemReport = new javax.swing.JMenuItem();
        jMenuItemRecomendation = new javax.swing.JMenuItem();
        jMenuAgenda = new javax.swing.JMenu();
        jMenuItemRegisterHomeWork = new javax.swing.JMenuItem();
        jMenuItemRegisterExams = new javax.swing.JMenuItem();
        jMenuItemHomeWorkExams = new javax.swing.JMenuItem();
        jMenuCarts = new javax.swing.JMenu();
        jMenuItemRegisterQuestions = new javax.swing.JMenuItem();
        jMenuItemStudie = new javax.swing.JMenuItem();
        jMenuProfile = new javax.swing.JMenu();
        jMenuItemProfile = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\NetBeansProjects\\ProyectoFinal\\src\\Recursor\\LogotipoLetrasBlancas.png")); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(43, 43, 43))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jMenuReturn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\NetBeansProjects\\EduPlanner\\src\\Recursor\\ReturnIcon.png")); // NOI18N

        jMenuItemReturn.setText("Regresar");
        jMenuItemReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReturnActionPerformed(evt);
            }
        });
        jMenuReturn.add(jMenuItemReturn);

        jMenuBar1.add(jMenuReturn);

        jMenuCalAverage.setText("Calculadora de promedio");

        jMenuItemRegisterSubject.setText("Registrar materia");
        jMenuItemRegisterSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegisterSubjectActionPerformed(evt);
            }
        });
        jMenuCalAverage.add(jMenuItemRegisterSubject);

        jMenuItemReport.setText("Reporte");
        jMenuItemReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReportActionPerformed(evt);
            }
        });
        jMenuCalAverage.add(jMenuItemReport);

        jMenuItemRecomendation.setText("Recomendaciones");
        jMenuItemRecomendation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRecomendationActionPerformed(evt);
            }
        });
        jMenuCalAverage.add(jMenuItemRecomendation);

        jMenuBar1.add(jMenuCalAverage);

        jMenuAgenda.setText("Agenda academica");

        jMenuItemRegisterHomeWork.setText("Registrar Tareas");
        jMenuItemRegisterHomeWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegisterHomeWorkActionPerformed(evt);
            }
        });
        jMenuAgenda.add(jMenuItemRegisterHomeWork);

        jMenuItemRegisterExams.setText("Registrar Examenes");
        jMenuItemRegisterExams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegisterExamsActionPerformed(evt);
            }
        });
        jMenuAgenda.add(jMenuItemRegisterExams);

        jMenuItemHomeWorkExams.setText("Tus tareas y examenes");
        jMenuItemHomeWorkExams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHomeWorkExamsActionPerformed(evt);
            }
        });
        jMenuAgenda.add(jMenuItemHomeWorkExams);

        jMenuBar1.add(jMenuAgenda);

        jMenuCarts.setText("Cartas de estudio");

        jMenuItemRegisterQuestions.setText("Ingresar preguntas");
        jMenuItemRegisterQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegisterQuestionsActionPerformed(evt);
            }
        });
        jMenuCarts.add(jMenuItemRegisterQuestions);

        jMenuItemStudie.setText("Estudiar");
        jMenuItemStudie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStudieActionPerformed(evt);
            }
        });
        jMenuCarts.add(jMenuItemStudie);

        jMenuBar1.add(jMenuCarts);

        jMenuProfile.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\NetBeansProjects\\EduPlanner\\src\\Recursor\\IconUser.png")); // NOI18N

        jMenuItemProfile.setText("Perfil");
        jMenuItemProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProfileActionPerformed(evt);
            }
        });
        jMenuProfile.add(jMenuItemProfile);

        jMenuBar1.add(jMenuProfile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemRegisterSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegisterSubjectActionPerformed
        JInternalFrameRegisterSubject registerSubject = new JInternalFrameRegisterSubject(list, pila, user);
        jDesktopPane1.add(registerSubject);
        registerSubject.show();
    }//GEN-LAST:event_jMenuItemRegisterSubjectActionPerformed

    private void jMenuItemReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReturnActionPerformed
        JFrameLogin login = new JFrameLogin(pila, user, list, listT, listE, listQ);
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItemReturnActionPerformed

    private void jMenuItemProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProfileActionPerformed
        JFrameProfile profile = new JFrameProfile(pila, user, list, listE, listT, listQ);
        profile.setVisible(true);
        profile.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItemProfileActionPerformed

    private void jMenuItemReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReportActionPerformed
        JInternalFrameReport report = new JInternalFrameReport(list);
        jDesktopPane1.add(report);
        report.show();
    }//GEN-LAST:event_jMenuItemReportActionPerformed

    private void jMenuItemRecomendationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRecomendationActionPerformed
        JInternalFrameRecommendations recommendation = new JInternalFrameRecommendations(list);
        jDesktopPane1.add(recommendation);
        recommendation.show();
    }//GEN-LAST:event_jMenuItemRecomendationActionPerformed

    private void jMenuItemRegisterHomeWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegisterHomeWorkActionPerformed
        JInternalFrameRegisterHomeWork homeWork = new JInternalFrameRegisterHomeWork(list, listT);
        jDesktopPane1.add(homeWork);
        homeWork.show();
    }//GEN-LAST:event_jMenuItemRegisterHomeWorkActionPerformed

    private void jMenuItemHomeWorkExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHomeWorkExamsActionPerformed
        JInternalFrameShowTasksExams showTE = new JInternalFrameShowTasksExams(listT, listE);
        jDesktopPane1.add(showTE);
        showTE.show();
    }//GEN-LAST:event_jMenuItemHomeWorkExamsActionPerformed

    private void jMenuItemRegisterExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegisterExamsActionPerformed
        JInternalFrameRegisterExams exams = new JInternalFrameRegisterExams(list, listE);
        jDesktopPane1.add(exams);
        exams.show();
    }//GEN-LAST:event_jMenuItemRegisterExamsActionPerformed

    private void jMenuItemRegisterQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegisterQuestionsActionPerformed
        JInternalFrameRegisterQuestions registerQuestions = new JInternalFrameRegisterQuestions(listQ);
        jDesktopPane1.add(registerQuestions);
        registerQuestions.show();
    }//GEN-LAST:event_jMenuItemRegisterQuestionsActionPerformed

    private void jMenuItemStudieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStudieActionPerformed
        JInternalFrameStudie studie = new JInternalFrameStudie(listQ);
        jDesktopPane1.add(studie);
        studie.show();
    }//GEN-LAST:event_jMenuItemStudieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrameMenu v1 = new JFrameMenu();
                v1.setVisible(true); //Permite ver la ventana
                v1.setLocationRelativeTo(null); //Centra la ventana en la pantalla del usuario
         
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuAgenda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuCalAverage;
    private javax.swing.JMenu jMenuCarts;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemHomeWorkExams;
    private javax.swing.JMenuItem jMenuItemProfile;
    private javax.swing.JMenuItem jMenuItemRecomendation;
    private javax.swing.JMenuItem jMenuItemRegisterExams;
    private javax.swing.JMenuItem jMenuItemRegisterHomeWork;
    private javax.swing.JMenuItem jMenuItemRegisterQuestions;
    private javax.swing.JMenuItem jMenuItemRegisterSubject;
    private javax.swing.JMenuItem jMenuItemReport;
    private javax.swing.JMenuItem jMenuItemReturn;
    private javax.swing.JMenuItem jMenuItemStudie;
    private javax.swing.JMenu jMenuProfile;
    private javax.swing.JMenu jMenuReturn;
    // End of variables declaration//GEN-END:variables
}
