/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.eduplanner;

import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.plaf.OptionPaneUI;
import javax.swing.table.DefaultTableModel;

public class JInternalFrameShowTasksExams extends javax.swing.JInternalFrame {

    private ListTasks listT;
    private ListExams listE;
    private String nameTask;
    private String nameExam;
    
    public JInternalFrameShowTasksExams(ListTasks listT, ListExams listE) {
        initComponents();
        
        this.listT = listT;
        this.listE = listE;
        
        //AGREGANDO LAS TAREAS A LA TABLA DE TAREAS 
        DefaultTableModel tasks = new DefaultTableModel();
        String[] header = {"Materia", "Nombre", "Fecha de entrega", "Ponderacion"};
        tasks.setColumnIdentifiers(header);
        NodoTasks current = listT.head;
        while(current != null){
            Object[] row = new Object[20];
            row[0] = current.getSubject();
            row[1] = current.getActivityName();
            row[2] = current.getDay() + " De " + current.getMonth();
            row[3] = current.getWeighing() + "%";
            tasks.addRow(row);
            current = current.getNext();
        }
        jTable1.setModel(tasks);
        
        //AGREGANDO LOS EXAMENES A LA TABLA DE EXAMENES
        DefaultTableModel exams = new DefaultTableModel();
        String[] header2 = {"Materia", "Nombre", "Fecha de entrega", "Ponderacion"};
        exams.setColumnIdentifiers(header2);
        NodoExams current2 = listE.head;
        while(current2 != null){
            Object[] row2 = new Object[20];
            row2[0] = current2.getSubject();
            row2[1] = current2.getActivityName();
            row2[2] = current2.getDay() + " De " + current2.getMonth();
            row2[3] = current2.getWeighing() + "%";
            exams.addRow(row2);
            current2 = current2.getNext();
        }
        jTable2.setModel(exams);
        
        ImageIcon img = new ImageIcon("C:\\Users\\Diego\\Documents\\NetBeansProjects\\ProyectoFinal\\src\\Recursor\\Cursores\\Cursor2.png");
        
        Cursor c;
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        c = tk.createCustomCursor(img.getImage(), new Point(1,1), null);
        
        jButtonDeleteTask.setCursor(c);
        jButtonDeleteExams.setCursor(c);
        jButtonUpdate.setCursor(c);
    }
    public JInternalFrameShowTasksExams(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonDeleteTask = new javax.swing.JButton();
        jButtonDeleteExams = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tus tareas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Tus examenes");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButtonDeleteTask.setText("Eliminar tarea");
        jButtonDeleteTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteTaskActionPerformed(evt);
            }
        });

        jButtonDeleteExams.setText("Eliminar examen");
        jButtonDeleteExams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteExamsActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Actualizar");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDeleteTask)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteExams)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonUpdate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeleteTask)
                    .addComponent(jButtonDeleteExams)
                    .addComponent(jButtonUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteTaskActionPerformed
        nameTask = JOptionPane.showInputDialog("Escribe el nombre de la tarea que deseas eliminar: ");
        
        listT.delete(nameTask);
        
    }//GEN-LAST:event_jButtonDeleteTaskActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        //AGREGANDO LAS TAREAS A LA TABLA DE TAREAS 
        DefaultTableModel tasks = new DefaultTableModel();
        String[] header = {"Materia", "Nombre", "Fecha de entrega", "Ponderacion"};
        tasks.setColumnIdentifiers(header);
        NodoTasks current = listT.head;
        while(current != null){
            Object[] row = new Object[20];
            row[0] = current.getSubject();
            row[1] = current.getActivityName();
            row[2] = current.getDay() + " De " + current.getMonth();
            row[3] = current.getWeighing() + "%";
            tasks.addRow(row);
            current = current.getNext();
        }
        jTable1.setModel(tasks);
        
        //AGREGANDO LOS EXAMENES A LA TABLA DE EXAMENES
        DefaultTableModel exams = new DefaultTableModel();
        String[] header2 = {"Materia", "Nombre", "Fecha de entrega", "Ponderacion"};
        exams.setColumnIdentifiers(header2);
        NodoExams current2 = listE.head;
        while(current2 != null){
            Object[] row2 = new Object[20];
            row2[0] = current2.getSubject();
            row2[1] = current2.getActivityName();
            row2[2] = current2.getDay() + " De " + current2.getMonth();
            row2[3] = current2.getWeighing() + "%";
            exams.addRow(row2);
            current2 = current2.getNext();
        }
        jTable2.setModel(exams);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteExamsActionPerformed
        nameExam = JOptionPane.showInputDialog("Escribe el nombre del examen que deseas eliminar");
        
        listE.delete(nameExam);
        
    }//GEN-LAST:event_jButtonDeleteExamsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteExams;
    private javax.swing.JButton jButtonDeleteTask;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
