/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.eduplanner;

import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class JInternalFrameRegisterExams extends javax.swing.JInternalFrame {

    public ListSubject list;
    public ListExams listE;
    private String[] array1 = {"1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"};
    private String[] array2 = {"1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28"};
    private String[] array3 = {"1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"};
    
    private String subject;
    private String activityName;
    private int weighing;
    private String weighingString;
    private String dayString;
    private int day;
    private String month;
    
    public JInternalFrameRegisterExams(ListSubject list, ListExams listE) {
        initComponents();
        
        this.listE = listE;
        this.list = list;
        
        
        ////////AGREGA LAS MATERIAS EN EL COMBOBOX///////////////   
        NodoSubjects aux = list.head;
        
        while(aux != null){
            jComboBoxSubjectHomeWork.addItem(aux.getSubject());
            aux = aux.getNext();
        }
        
        ImageIcon img = new ImageIcon("C:\\Users\\Diego\\Documents\\NetBeansProjects\\ProyectoFinal\\src\\Recursor\\Cursores\\Cursor2.png");
        
        Cursor c;
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        c = tk.createCustomCursor(img.getImage(), new Point(1,1), null);
        
        jComboBoxSubjectHomeWork.setCursor(c);
        jComboBoxMonth.setCursor(c);
        jComboBoxDay.setCursor(c);
        jButtonRegisterHomeWork.setCursor(c);
    }
    
    public JInternalFrameRegisterExams(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxMonth = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxSubjectHomeWork = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButtonRegisterHomeWork = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxDay = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldWeighing = new javax.swing.JTextField();
        jTextFieldNameHomeWork = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel3.setText("Nombre del examen:");

        jLabel4.setText("Fecha de entrega: ");

        jComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBoxMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMonthActionPerformed(evt);
            }
        });

        jLabel5.setText("Dia:");

        jLabel6.setText("Mes:");

        jButtonRegisterHomeWork.setText("Registrar");
        jButtonRegisterHomeWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterHomeWorkActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Examenes");

        jComboBoxDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDayActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingresa la materia del examen:");

        jLabel7.setText("Ponderacion del examen:");

        jTextFieldWeighing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWeighingActionPerformed(evt);
            }
        });
        jTextFieldWeighing.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldWeighingKeyTyped(evt);
            }
        });

        jTextFieldNameHomeWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameHomeWorkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(jButtonRegisterHomeWork)
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxSubjectHomeWork, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldNameHomeWork, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldWeighing, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSubjectHomeWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNameHomeWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldWeighing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegisterHomeWork))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMonthActionPerformed
        if(jComboBoxMonth.getSelectedItem().equals("Enero") || jComboBoxMonth.getSelectedItem().equals("Marzo")
            || jComboBoxMonth.getSelectedItem().equals("Mayo") || jComboBoxMonth.getSelectedItem().equals("Julio")
            || jComboBoxMonth.getSelectedItem().equals("Agosto") || jComboBoxMonth.getSelectedItem().equals("Octubre")
            || jComboBoxMonth.getSelectedItem().equals("Diciembre")){
            for(int i = 0; i<array1.length; i++){
                jComboBoxDay.addItem(array1[i]);
            }
        }
        if(jComboBoxMonth.getSelectedItem().equals("Febrero")){
            for(int i = 0; i<array2.length; i++){
                jComboBoxDay.addItem(array2[i]);
            }
        }
        if(jComboBoxMonth.getSelectedItem().equals("Abril") || jComboBoxMonth.getSelectedItem().equals("Junio")
            || jComboBoxMonth.getSelectedItem().equals("Septiembre") || jComboBoxMonth.getSelectedItem().equals("Noviembre")){
            for(int i = 0; i<array3.length; i++){
                jComboBoxDay.addItem(array3[i]);
            }
        }
    }//GEN-LAST:event_jComboBoxMonthActionPerformed

    private void jButtonRegisterHomeWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterHomeWorkActionPerformed
        if(jComboBoxMonth.getSelectedItem() == null || jComboBoxDay.getSelectedItem() == null || jComboBoxSubjectHomeWork.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "Llena todos los espacios");
        }else{
            subject = jComboBoxSubjectHomeWork.getSelectedItem().toString();
            activityName = jTextFieldNameHomeWork.getText();
            month = jComboBoxMonth.getSelectedItem().toString();
            dayString = jComboBoxDay.getSelectedItem().toString();
            weighingString = jTextFieldWeighing.getText();
            
            if(subject.isEmpty() || jTextFieldNameHomeWork.getText().isEmpty() || jTextFieldWeighing.getText().isEmpty()
                    || month.isEmpty() || dayString.isEmpty()){
                JOptionPane.showMessageDialog(this, "Llena todos los espacios");
            }else{
                day = Integer.parseInt(dayString);
                weighing = Integer.parseInt(weighingString);

                listE.add(subject, activityName, weighing, day, month);

                JOptionPane.showMessageDialog(this, "Registro exitoso");
            }
        }
    }//GEN-LAST:event_jButtonRegisterHomeWorkActionPerformed

    private void jComboBoxDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDayActionPerformed

    }//GEN-LAST:event_jComboBoxDayActionPerformed

    private void jTextFieldNameHomeWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameHomeWorkActionPerformed
        jTextFieldWeighing.requestFocus();
    }//GEN-LAST:event_jTextFieldNameHomeWorkActionPerformed

    private void jTextFieldWeighingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWeighingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWeighingActionPerformed

    private void jTextFieldWeighingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldWeighingKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
        if(jTextFieldWeighing.getText().length() >= 3){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldWeighingKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegisterHomeWork;
    private javax.swing.JComboBox<String> jComboBoxDay;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JComboBox<String> jComboBoxSubjectHomeWork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldNameHomeWork;
    private javax.swing.JTextField jTextFieldWeighing;
    // End of variables declaration//GEN-END:variables
}
