/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestordedistribucion;

import java.awt.Cursor;
import javax.swing.ImageIcon;
import java.awt.Point;
import java.awt.Toolkit;

public class JFrameCalculadora extends javax.swing.JFrame {
    
    private int num1;
    private int num2;
    
    ImagenFondo fondo;
    
    public JFrameCalculadora() {
        fondo = new ImagenFondo("C:\\Users\\Diego\\Desktop\\Calculadora\\Fondo.png");
        this.setContentPane(fondo);
        initComponents();
        
        
        ////////////////CURSOR 1//////////////////////////////
        
        ImageIcon img = new ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\Cursor.png");
        
        Cursor c;
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        
        c = tk.createCustomCursor(img.getImage(), new Point(1, 1), null);
        
        jButto0.setCursor(c);
        jButto1.setCursor(c);
        jButto2.setCursor(c);
        jButto3.setCursor(c);
        jButto4.setCursor(c);
        jButton5.setCursor(c);
        jButton6.setCursor(c);
        jButto7.setCursor(c);
        jButto8.setCursor(c);
        jButto9.setCursor(c);
        
        ////////////////CURSOR 2//////////////////////////////

        ImageIcon img2 = new ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\Cursor2.png");
        
        Cursor c2;
        
        Toolkit tk2 = Toolkit.getDefaultToolkit();
        
        c2 = tk2.createCustomCursor(img2.getImage(), new Point(1, 1), null);
        
        jButtonSuma.setCursor(c2);
        jButtonResta.setCursor(c2);
        jButtonMultiplicacion.setCursor(c2);
        
        ////////////////CURSOR 3//////////////////////////////
        
        ImageIcon img3 = new ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\Cursor3.png");
        
        Cursor c3;
        
        Toolkit tk3 = Toolkit.getDefaultToolkit();
        
        c3 = tk3.createCustomCursor(img3.getImage(), new Point(1, 1), null);
        
        jButtonPotencia.setCursor(c3);
        jButtonDivision.setCursor(c3);
        jButtonModulo.setCursor(c3);
        
        ////////////////CURSOR 4//////////////////////////////
        
        ImageIcon img4 = new ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\CursorBorrar.png");
        
        Cursor c4;
        
        Toolkit tk4 = Toolkit.getDefaultToolkit();
        
        c4 = tk4.createCustomCursor(img4.getImage(), new Point(1, 1), null);
        
        jButtonBorrar.setCursor(c4);
        
        ////////////////Titulo de la aplicacion//////////////////////////////
        
        setTitle("Gestor de distribucion");
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        // Icono para la aplicación
        setIconImage(new ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\Titulo.png").getImage());

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButto7 = new javax.swing.JButton();
        jButto8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButto9 = new javax.swing.JButton();
        jButto4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButto3 = new javax.swing.JButton();
        jButto2 = new javax.swing.JButton();
        jButto1 = new javax.swing.JButton();
        jButtonSuma = new javax.swing.JButton();
        jButtonResta = new javax.swing.JButton();
        jButtonMultiplicacion = new javax.swing.JButton();
        jButto0 = new javax.swing.JButton();
        jButtonPotencia = new javax.swing.JButton();
        jButtonModulo = new javax.swing.JButton();
        jButtonDivision = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButto7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\7number_7_3074.png")); // NOI18N
        jButto7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButto7ActionPerformed(evt);
            }
        });

        jButto8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\8number_8_3824.png")); // NOI18N
        jButto8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButto8ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButto9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\9number_9_3071.png")); // NOI18N
        jButto9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButto9ActionPerformed(evt);
            }
        });

        jButto4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\4number_4_3829.png")); // NOI18N
        jButto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButto4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\5_number_3827.png")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\6_number_3075.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButto3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\3number_3_3077.png")); // NOI18N
        jButto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButto3ActionPerformed(evt);
            }
        });

        jButto2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\2number_2_3079.png")); // NOI18N
        jButto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButto2ActionPerformed(evt);
            }
        });

        jButto1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\1number_1_3831.png")); // NOI18N
        jButto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButto1ActionPerformed(evt);
            }
        });

        jButtonSuma.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\Suma.png")); // NOI18N
        jButtonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumaActionPerformed(evt);
            }
        });

        jButtonResta.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\Resta.png")); // NOI18N
        jButtonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaActionPerformed(evt);
            }
        });

        jButtonMultiplicacion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\Multiplicacion.png")); // NOI18N
        jButtonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicacionActionPerformed(evt);
            }
        });

        jButto0.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\cero.png")); // NOI18N
        jButto0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButto0ActionPerformed(evt);
            }
        });

        jButtonPotencia.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\math_format_professional_filled_icon_202082.png")); // NOI18N
        jButtonPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPotenciaActionPerformed(evt);
            }
        });

        jButtonModulo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\percentage_icon_217839.png")); // NOI18N
        jButtonModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModuloActionPerformed(evt);
            }
        });

        jButtonDivision.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\Division.png")); // NOI18N
        jButtonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisionActionPerformed(evt);
            }
        });

        jButtonIgual.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\Igual.png")); // NOI18N
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jButtonBorrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\Calculadora\\Borrar.png")); // NOI18N
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButto7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButto8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButto9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButto0)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonPotencia))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButto4)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton5))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButto1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButto2)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButto3)
                                            .addComponent(jButton6)
                                            .addComponent(jButtonModulo))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSuma)
                                    .addComponent(jButtonResta)
                                    .addComponent(jButtonMultiplicacion)
                                    .addComponent(jButtonDivision)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonIgual)
                                    .addComponent(jButtonBorrar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonIgual))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButto8)
                            .addComponent(jButto7)
                            .addComponent(jButto9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButto4)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButto3)
                            .addComponent(jButto2)
                            .addComponent(jButto1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButto0)
                            .addComponent(jButtonPotencia)
                            .addComponent(jButtonModulo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSuma)
                                .addGap(77, 77, 77))
                            .addComponent(jButtonResta))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMultiplicacion)
                        .addGap(77, 77, 77))
                    .addComponent(jButtonDivision, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButto7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButto7ActionPerformed
        jTextArea1.append("7");
    }//GEN-LAST:event_jButto7ActionPerformed

    private void jButto8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButto8ActionPerformed
        jTextArea1.append("8");
    }//GEN-LAST:event_jButto8ActionPerformed

    private void jButto9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButto9ActionPerformed
        jTextArea1.append("9");
    }//GEN-LAST:event_jButto9ActionPerformed

    private void jButto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButto4ActionPerformed
        jTextArea1.append("4");
    }//GEN-LAST:event_jButto4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextArea1.append("5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextArea1.append("6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButto3ActionPerformed
        jTextArea1.append("3");
    }//GEN-LAST:event_jButto3ActionPerformed

    private void jButto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButto2ActionPerformed
        jTextArea1.append("2");
    }//GEN-LAST:event_jButto2ActionPerformed

    private void jButto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButto1ActionPerformed
        jTextArea1.append("1");
    }//GEN-LAST:event_jButto1ActionPerformed

    private void jButtonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumaActionPerformed
        num1 = Integer.parseInt(jTextArea1.getText());
        jTextArea1.setText("");
        jLabel1.setText("Sumando");
    }//GEN-LAST:event_jButtonSumaActionPerformed

    private void jButtonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaActionPerformed
        num1 = Integer.parseInt(jTextArea1.getText());
        jTextArea1.setText("");
        jLabel1.setText("Restando");
    }//GEN-LAST:event_jButtonRestaActionPerformed

    private void jButtonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicacionActionPerformed
        num1 = Integer.parseInt(jTextArea1.getText());
        jTextArea1.setText("");
        jLabel1.setText("Multiplicando");
    }//GEN-LAST:event_jButtonMultiplicacionActionPerformed

    private void jButto0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButto0ActionPerformed
        jTextArea1.append("0");
    }//GEN-LAST:event_jButto0ActionPerformed

    private void jButtonPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPotenciaActionPerformed
        num1 = Integer.parseInt(jTextArea1.getText());
        jTextArea1.setText("");
        jLabel1.setText("Potencia");
    }//GEN-LAST:event_jButtonPotenciaActionPerformed

    private void jButtonModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModuloActionPerformed
        num1 = Integer.parseInt(jTextArea1.getText());
        jTextArea1.setText("");
        jLabel1.setText("Modulo");
    }//GEN-LAST:event_jButtonModuloActionPerformed

    private void jButtonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisionActionPerformed
        num1 = Integer.parseInt(jTextArea1.getText());
        jTextArea1.setText("");
        jLabel1.setText("Dividiendo");
    }//GEN-LAST:event_jButtonDivisionActionPerformed

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
       
        num2 = Integer.parseInt(jTextArea1.getText());
        
        if(jLabel1.getText().equals("Sumando")){
            int resultado = num1 + num2;
            jTextArea1.setText(String.valueOf(resultado));
        }
        if(jLabel1.getText().equals("Restando")){
            int resultado = num1 - num2;
            jTextArea1.setText(String.valueOf(resultado));
        }
        if(jLabel1.getText().equals("Multiplicando")){
            int resultado = num1 * num2;
            jTextArea1.setText(String.valueOf(resultado));
        }
        if(jLabel1.getText().equals("Dividiendo")){
            int resultado = num1 / num2;
            jTextArea1.setText(String.valueOf(resultado));
        }
        if(jLabel1.getText().equals("Potencia")){
            double resultado = Math.pow(num1, num2);
            jTextArea1.setText(String.valueOf(resultado));
        }
        if(jLabel1.getText().equals("Modulo")){
            int resultado = num1 % num2;
            jTextArea1.setText(String.valueOf(resultado));
        }
        
        jLabel1.setText("");
    }//GEN-LAST:event_jButtonIgualActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        jTextArea1.setText("");
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButto0;
    private javax.swing.JButton jButto1;
    private javax.swing.JButton jButto2;
    private javax.swing.JButton jButto3;
    private javax.swing.JButton jButto4;
    private javax.swing.JButton jButto7;
    private javax.swing.JButton jButto8;
    private javax.swing.JButton jButto9;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonDivision;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonModulo;
    private javax.swing.JButton jButtonMultiplicacion;
    private javax.swing.JButton jButtonPotencia;
    private javax.swing.JButton jButtonResta;
    private javax.swing.JButton jButtonSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
